networks:
  d2ray_br:
    external: false

services:
  d2ray:
    image: quackerd/d2ray
    container_name: d2ray
    ports:
      - 8443:8443
    environment:
      - HOST=myvps.com
      - PORT=8443
      - TARGET_HOST=www.apple.com
      - TARGET_PORT=443
      - TARGET_SNI=www.apple.com,apple.com
      - USERS=alice,bob,eve
      - PRIVATE_KEY=KE5MCI5e395fub55O1lsNPzvWw9nNAyCaecRSp3BvHg # Do NOT use this random key
      - LOG_LEVEL=warn
    restart: unless-stopped
    networks:
      - d2ray_br
    volumes:
      - ./config:/etc/d2ray
